config/routes.rb
Rails.application.routes.draw do
  
  get 'events/near'

  devise_for :clients
  
  get 'home/index'
  get 'events/near'
  get 'events/next'
  get 'tickets/list'
  get 'tickets/show'
  get 'clients/show'
  post 'clients/add_address'
  post 'clients/add_credit_card'
  post 'clients/get_session'
  get 'clients/info'
  post 'clients/create'
  post 'clients/exists'
  post 'clients/update_password'
  post 'orders/create'
  get 'orders/list'
  post 'orders/request_refund'
  
  get 'contact/send_message'
  get 'contact/send_email_message'

  resources :search, :signature, :league_test
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)
  get '/admin/performers/new/quick_add' => 'admin/performers#quick_add', as: :admin_performer_quick_add
  post '/admin/performers/quick_create' => 'admin/performers#quick_create', as: :admin_performer_quick_create

  get '/admin/performers/:id/edit/quick_edit' => 'admin/performers#quick_edit', as: :admin_performer_quick_edit
  patch '/admin/performers/:id/quick_update' => 'admin/performers#quick_update', as: :admin_performer_quick_update

  root "home#index"
  

  namespace :api do
    namespace :v1 do
      resources :clients, :defaults => { :format => 'json' }
      resources :events, :defaults => { :format => 'json' }
      resources :orders, :defaults => { :format => 'json' }
      resources :order_stats, :defaults => { :format => 'json' }
      resources :performers, :defaults => { :format => 'json' }
      resources :divisions, :defaults => { :format => 'json' }
      resources :sports, :defaults => { :format => 'json' }
      resources :tiles, :defaults => { :format => 'json' }
      resources :venues, :defaults => { :format => 'json' }
      resources :testimonials, :defaults => { :format => 'json' }
      resources :promo_codes, :defaults => { :format => 'json' }
      resources :service_fees, :defaults => { :format => 'json' }
    end
  end
  
  match "*path" => "home#index", via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="gamehedge">
  <head>
    <title ng-bind="$root.title"></title>
    <meta name="description" content="{{$root.description}}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    <meta name="fragment" content="!">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="preload" href="https://fonts.googleapis.com/css?family=Montserrat:400,700" as="style" onload="this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700"></noscript>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"></script>

      
   <!--  <script type="text/javascript" src="https://code.jquery.com/jquery-migrate-3.0.0.min.js"></script>-->


   <!--  <link rel="preload" href="https://dynamicvenuemaps.com/maps/css/style_maps.css" as="style" onload="this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="https://dynamicvenuemaps.com/maps/css/style_maps.css"></noscript> -->
      
    <%= csrf_meta_tags %>
      
    <style>
      .intro-full {
          width: 100%;
          height: 100%;
          position: fixed;
          z-index: 9999999999999;
          background-color: black;
      }

      .intro-img-container{
          position: absolute;
          width: 300px;
          height: 60px;
          top: 50%;
          left: 50%;
          margin-left: -150px;
          margin-top: -30px;
      }  
    </style>
      <!-- begin olark code -->
  <noscript><a href="https://www.olark.com/site/2065-539-10-9682/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
  <!-- end olark code -->

<script src="//cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/qtip2/3.0.3/jquery.qtip.min.css">



<script>
  var QueryString = function () {
  // This function is anonymous, is executed immediately and 
  // the return value is assigned to QueryString!
  var query_string = {};
  var query = window.location.search.substring(1);
  var vars = query.split("&");
  for (var i=0;i<vars.length;i++) {
    var pair = vars[i].split("=");
        // If first entry with this name
    if (typeof query_string[pair[0]] === "undefined") {
      query_string[pair[0]] = decodeURIComponent(pair[1]);
        // If second entry with this name
    } else if (typeof query_string[pair[0]] === "string") {
      var arr = [ query_string[pair[0]],decodeURIComponent(pair[1]) ];
      query_string[pair[0]] = arr;
        // If third or later entry with this name
    } else {
      query_string[pair[0]].push(decodeURIComponent(pair[1]));
    }
  } 
  return query_string;
  }();
 
  

  var host_base = window.location.hostname;  
  var mxpnl_id = "08f62d786d58b558399462b5f5dd843f";
  console.log('Reg mxp');
  if(host_base.indexOf("gamehedge.com") == -1){
    mxpnl_id = "4b7832a4489a00193f53083b54e3defd";
    console.log('Stg mxp');
  
  }

var enable_moengage = 1;

//alert(document.referrer);
//console.log('Ref:'+document.referrer);
  //Check for govx cookie and set vars
    var govxcookie = '';
    var nameEQ5 = "isghgovx" + "=";
    var ca5 = document.cookie.split(';');
    for(var i5=0;i5 < ca5.length;i5++) {
        var c5 = ca5[i5];
        while (c5.charAt(0)==' ') c5 = c5.substring(1,c5.length);
        if (c5.indexOf(nameEQ5) == 0) {
            govxcookie = c5.substring(nameEQ5.length,c5.length);
        }
    }
    if(govxcookie == "1"){
         enable_moengage = 0;
         mxpnl_id = "1d93c1c371ff3b55b53e887936b5e926";
         console.log('gx mxp');
    }else{
              if(document.referrer.indexOf("govx") > -1){
                mxpnl_id = "1d93c1c371ff3b55b53e887936b5e926";
                console.log('gx mxp');
                enable_moengage = 0;
              }
      
    }




  
</script>
<!-- start Mixpanel --><script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
mixpanel.init(mxpnl_id);</script><!-- end Mixpanel -->      


<link rel="manifest" href="/manifest.json"> 
<script type="text/javascript" src="https://cdn.moengage.com/webpush/moe_webSdk.min.latest.js"></script> 
<script type="text/javascript"> 
    if(enable_moengage == "1"){
        Moengage = moe( { app_id: "X56DG7CUCZM9MX10V09IG605", debug_logs: 0 }); 
    }
</script>


<script>
function getBrowserWidth(){
   return window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth||0;
}
function getBrowserHeight(){
   return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight||0;
}
</script>


<script type="text/javascript">
  var mxpnl_super_props = {};
  var mxpnl_props = {};


  mxpnl_super_props.AdChannel = 'none';
  mxpnl_super_props.AdCmp = 'none';
  mxpnl_super_props.AdGroup = 'none';
  mxpnl_super_props.AdAB = 'none';
  mxpnl_super_props.AdData = 'none';
  mxpnl_super_props.AdData2 = 'none';
  mxpnl_super_props.ScreenResolution = 'not detected';
  
  if (QueryString.adchannel != undefined){
    mxpnl_super_props.AdChannel = QueryString.adchannel;
  }
  if (QueryString.adcmp != undefined){
    mxpnl_super_props.AdCmp = QueryString.adcmp;
  }
  if (QueryString.adgroup != undefined){
    mxpnl_super_props.AdGroup = QueryString.adgroup;
  }
  if (QueryString.adab != undefined){
    mxpnl_super_props.AdAB = QueryString.adab;
  }
  if (QueryString.addata != undefined){
    mxpnl_super_props.AdData = QueryString.addata;
  }
  if (QueryString.addata2 != undefined){
    mxpnl_super_props.AdData2 = QueryString.addata2;
  }
  
  mxpnl_super_props.ScreenResolution = screen.width+'x'+ screen.height;
  mxpnl_props.BrowserWSize = getBrowserWidth()+'x'+ getBrowserHeight();

  mixpanel.register_once(mxpnl_super_props);
  mixpanel.register(mxpnl_props);

  /*
  var fvd = (new Date).toISOString();
  mixpanel.register_once({
        "FirstVisitDate3": fvd.toString()
  });
  */




</script>


<script>
mixpanel.track("GameHedge Visit");
</script>
      <!-- Facebook Pixel Code 
    
      <noscript><img height="1" width="1" style="display:none"
      src="https://www.facebook.com/tr?id=1221171167912729&ev=PageView&noscript=1" alt="Facebook"
      /></noscript>
       End Facebook Pixel Code -->



    <!-- Start Visual Website Optimizer Asynchronous Code -->
    <script type='text/javascript'>
    var _vwo_clicks=10;
    var _vwo_code=(function(){
    var account_id=271095,
    settings_tolerance=2000,
    library_tolerance=2500,
    use_existing_jquery=false,
    // DO NOT EDIT BELOW THIS LINE
    f=false,d=document;return{use_existing_jquery:function(){return use_existing_jquery;},library_tolerance:function(){return library_tolerance;},finish:function(){if(!f){f=true;var a=d.getElementById('_vis_opt_path_hides');if(a)a.parentNode.removeChild(a);}},finished:function(){return f;},load:function(a){var b=d.createElement('script');b.src=a;b.type='text/javascript';b.innerText;b.onerror=function(){_vwo_code.finish();};d.getElementsByTagName('head')[0].appendChild(b);},init:function(){settings_timer=setTimeout('_vwo_code.finish()',settings_tolerance);var a=d.createElement('style'),b='body{opacity:0 !important;filter:alpha(opacity=0) !important;background:none !important;}',h=d.getElementsByTagName('head')[0];a.setAttribute('id','_vis_opt_path_hides');a.setAttribute('type','text/css');if(a.styleSheet)a.styleSheet.cssText=b;else a.appendChild(d.createTextNode(b));h.appendChild(a);this.load('//dev.visualwebsiteoptimizer.com/j.php?a='+account_id+'&u='+encodeURIComponent(d.URL)+'&r='+Math.random());return settings_timer;}};}());_vwo_settings_timer=_vwo_code.init();
    </script>
    <!-- End Visual Website Optimizer Asynchronous Code -->
  </head>
      
  <body ng-class="{'no-scrolling': $root.showMenu}" >
    <div class="hidden" ng-controller="MainScreenController">
      <div id="initial_scripts">
        
      </div>
    </div>
    <script type="text/javascript">
      var info_url = "<%= image_url 'icon__info_1x.png' %>";
    </script>
    <%= yield %>
    <p class="notice hidden"><%= notice %></p>
    <p class="alert hidden"><%= alert %></p>
    
    <noscript><img src="//bat.bing.com/action/0?ti=5255950&Ver=2" height="0" width="0" style="display:none; visibility: hidden;" /></noscript>
        
    <!-- Twitter universal website tag code -->
 
    <!-- End Twitter universal website tag code -->
    <div id="mcafee-seal" class="hidden">
      <script src="https://cdn.ywxi.net/js/inline.js?w=74"></script>
    </div>
    <script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>
    <!-- Facebook Pixel Code -->


<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '1833492870222595'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1833492870222595&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->


<!-- SOF WSM Call Tracking -->
<script type="text/javascript">
   var _stk = "ae9261cf2f8dcc0b7257f19a260e71c6cdbf7364";
   (function(){
       var a=document, b=a.createElement("script"); b.type="text/javascript";
       b.async=!0; b.src=('https:'==document.location.protocol ? 'https://' :
       'http://') + 'd31y97ze264gaa.cloudfront.net/assets/st/js/st.js';
       a=a.getElementsByTagName("script")[0]; a.parentNode.insertBefore(b,a);
   })();
</script>
<!-- EOF WSM Call Tracking -->


<script>(function(w,d,t,r,u){var f,n,i;w[u]=w[u]||[],f=function(){var o={ti:"5598481"};o.q=w[u],w[u]=new UET(o),w[u].push("pageLoad")},n=d.createElement(t),n.src=r,n.async=1,n.onload=n.onreadystatechange=function(){var s=this.readyState;s&&s!=="loaded"&&s!=="complete"||(f(),n.onload=n.onreadystatechange=null)},i=d.getElementsByTagName(t)[0],i.parentNode.insertBefore(n,i)})(window,document,"script","//bat.bing.com/bat.js","uetq");</script><noscript><img src="//bat.bing.com/action/0?ti=5598481&Ver=2" height="0" width="0" style="display:none; visibility: hidden;" /></noscript>




  </body>
</html>